name: MolTrans_2020
model_params:
  max_drug_seq: 50
  max_protein_seq: 545
  input_dim_drug: 23532
  input_dim_target: 16693
  emb_size: 384
  dropout_rate: 0.1
  batch_size: 16
  #DenseNet
  scale_down_ratio: 0.25
  growth_rate: 20
  transition_rate: 0.5
  num_dense_blocks: 4
  kernal_dense_size: 3
  # Encoder
  intermediate_size: 1536
  num_attention_heads: 12
  attention_probs_dropout_prob: 0.1
  hidden_dropout_prob: 0.1
  flat_dim: 78192
preprocess_params:
  max_drug_seq: 50
  max_protein_seq: 545
batch_size: 16
epoch: 10
